[
build-system
]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[
project
]
name = "helmet"
version = "0.1.0"
description = "HELMET: Boosting LLM with Hierarchical Evaluation"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.30.0",
    "datasets>=2.12.0",
    "accelerate>=0.20.0",
    "pydantic>=2.0.0",
    "typing-extensions>=4.5.0",
    "numpy>=1.24.0",
    "pandas>=1.5.0",
    "tqdm>=4.65.0",
    "python-dotenv>=1.0.0",
    "PyYAML>=6.0",
    "requests>=2.31.0",
]

[
project.optional-dependencies
]
dev = [
    "black>=23.3.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "pytest>=7.3.1",
    "pytest-cov>=4.1.0",
]

[
project.urls
]
"Homepage" = "https://github.com/yourusername/HELMET"
"Bug Tracker" = "https://github.com/yourusername/HELMET/issues"

[
tool.setuptools.packages.find
]
include = ["helmet", "helmet.*"]

[
tool.setuptools.package-data
]
helmet = ["config/*.yaml", "tasks/*.json"]

[
project.scripts
]
helmet-eval = "helmet.utils.eval:main"
helmet-eval-alce = "helmet.utils.eval_alce:main"
helmet-collect = "scripts.collect_results:main"
helmet-generate = "scripts.generate_completions:main"

[
tool.black
]
line-length = 100
target-version = ["py38"]
include = '\.pyi?$'

[
tool.isort
]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true

[
tool.pytest.ini_options
]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "-ra -q --cov=helmet"